version: "3"

volumes:
  db: # mount it internally instead of a folder. it avoids file lock problems

services:
  backend:
    build: ./chequer-board-api
    env_file:
      - prod.env
    links:
      - mysql:$DB_HOST
    depends_on:
      - mysql
    container_name: chequer-board-api
    restart: always
    ports:
      - "$PORT:$PORT"

  mysql:
    env_file:
      - prod.env
    image: mysql:8
    restart: always
    container_name: $DB_HOST
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_DATABASE

  frontend:
    build: ./chequer-board-front
    restart: always
    links:
      - backend:4500
    depends_on:
      - backend
    container_name: chequer-board-front
    ports:
     - "80:80" 
