version: "3"

volumes:
  db: # mount it internally instead of a folder. it avoids file lock problems

services:
  app:
    build: .
    env_file:
      - prod.env
    links:
      - mysql:$DB_HOST
    depends_on:
      - mysql
    container_name: chequer-board
    restart: always
    ports:
      - "$PORT:$PORT"

  mysql:
    env_file:
      - prod.env
    image: mysql:8
    restart: always
    container_name: $DB_HOST
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_DATABASE

  # adminer:
  #   image: adminer
  #   restart: always
  #   links:
  #     - mysql
  #   ports:
  #    - "8081:8080" # to avoid conflicting the 8080 default for many cloud providers
